apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  ports:
  - port: 80
  selector:
    app: backend
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
---
apiVersion: v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: jmezach/team-assembler-backend:latest
        name: backend
        env:
          # Use secret in real usage
        - name: OutputFilePath
          value: /var/teams
        ports:
        - containerPort: 80
          name: backend
        volumeMounts:
        - name: backend-persistent-storage
          mountPath: /var/teams
      volumes:
      - name: backend-persistent-storage
        persistentVolumeClaim:
          claimName: backend-pv-claim
      nodeSelector:
        beta.kubernetes.io/os: linux